# Generated by Django 3.2.8 on 2022-05-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dorm', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.CharField(max_length=12, verbose_name='ИИН нөмер')),
                ('supplementary_description', models.CharField(max_length=512, verbose_name='Қосымша ақпарат')),
                ('profession', models.CharField(max_length=60, verbose_name='Мамандық атауы')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Жіберілген уақыт')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Жалға алушы')),
            ],
            options={
                'verbose_name': 'Өтініш',
                'verbose_name_plural': 'Өтінішдер',
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='RequestAppendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='img/order/request_appendix_file/', verbose_name='Қосымша құжат')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.request', verbose_name='Өтініш')),
            ],
            options={
                'verbose_name': 'Өтінішдің қосымша құжаты',
                'verbose_name_plural': 'Өтінішдің қосымша құжаттары',
                'db_table': 'request_appendix',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Баға')),
                ('duration', models.CharField(choices=[('hour', 'Сағат'), ('day', 'Күн'), ('month', 'Ай'), ('year', 'Жыл')], max_length=10, verbose_name='Мерзім түрі')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.bed', verbose_name='Төсек орын')),
            ],
            options={
                'verbose_name': 'Төлем ақы',
                'verbose_name_plural': 'Төлем ақылар',
                'db_table': 'rent',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=40, verbose_name='Тапсырыс нөмері')),
                ('status', models.BooleanField(default=False, verbose_name='Өтініш күйі')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.dorm', verbose_name='Жатақхана')),
                ('rent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.rent', verbose_name='Төлем ақы түрі')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.request', verbose_name='Өтініш')),
            ],
            options={
                'verbose_name': 'Тапсырыс',
                'verbose_name_plural': 'Тапсырысдар',
                'db_table': 'order',
            },
        ),
    ]
